dataset:
  name: 'video'
  args:
    video_path: /home/users/ntu/ccdsnirm/scratch/pokemon2.mp4
    dataset_dir: /home/users/ntu/ccdsnirm/projects/DiffuseNet/dataset/pokemon2 
    hf_cache_dir: /home/users/ntu/ccdsnirm/scratch
    interval: 2.0
    resolution: 256
    test_ratio: 0.2
    start: 60
    

model:
  in_ch: 3
  latent_dim: 64
  down_channels: [128, 128, 256, 256, 512, 512]  # num_down = len(down_channels)-1
  attn_channels: [512, 512]
  num_heads: 16
  n_layers: 2
  norm_type: "bn"
  norm_groups: 32
  activation: "elu"


training:
  seed: 42
  batch_size: 40
  epochs: 300
  lr: 0.00002
  grad_clip: 5.0
  weight_decay: 0.00001
  disc_start: 2000
  disc_weight: 0.5
  kl_weight: 0.000005
  percep_weight: 1
  num_samples: 8
  save_interval: 50
  ckpt_save_dir: /home/users/ntu/ccdsnirm/scratch/DiffuseNet/vae/ckpts/2.0/
  recon_img_save_dir: /home/users/ntu/ccdsnirm/scratch/DiffuseNet/vae/reconstructions/2.0/


wandb:
  project: 'VAE'
  name: 'train_vae-multi-gpu'