dataset:
  name: 'video'
  args:
    video_path: /home/users/ntu/ccdsnirm/scratch/pokemon2.mp4
    dataset_dir: /home/users/ntu/ccdsnirm/projects/DiffuseNet/dataset/pokemon2 
    hf_cache_dir: /home/users/ntu/ccdsnirm/scratch
    interval: 2.0
    resolution: 256
    test_ratio: 0.2
    start: 60


vae:
  in_ch: 3
  latent_dim: 64
  down_channels: [128, 128, 256, 256, 512, 512]
  attn_channels: [512, 512]
  num_heads: 16
  n_layers: 2
  norm_type: "bn"
  norm_groups: 32
  activation: "elu"
  vae_ckpt: /home/users/ntu/ccdsnirm/scratch/DiffuseNet/vae/ckpts/2.0/vae_epoch_300.pth


scheduler:
  beta_start: 0.0001
  beta_end: 0.02
  timesteps: 500


dit:
  latent_size: 8
  latent_ch: 64
  patch_size: 1
  embed_dim: 1920
  time_emb_dim: 1920
  num_layers: 24
  num_heads: 24
  mlp_ratio: 4
  cond_config:
    text_embed_model: 'clip'
    text_emb_dim: 512
    dropout_prob: 0.1
    

training:
  seed: 42
  batch_size: 72
  epochs: 1000
  lr: 0.0001
  weight_decay: 0.00001
  num_samples: 4
  ckpt_save_interval: 100
  sample_save_interval: 1
  vae_scale: 0.437
  cfg_guidance_scale: 7
  ckpt_save_dir: /home/users/ntu/ccdsnirm/scratch/DiT/ckpts/cfg-test-pokemon
  sample_save_dir: /home/users/ntu/ccdsnirm/scratch/DiT/samples/cfg-test-pokemon


wandb:
  project: 'DiT-CFG'
  name: 'train_DiT-cfg-test-pokemon'